import React, { useEffect, useState } from 'react';
import axios from 'axios';

// Component for handling Phone Verification via MSG91
const PhoneVerification = ({ token }) => {
  const [isVerified, setIsVerified] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    // 1. Inject the MSG91 SendOTP Widget script
    const script = document.createElement('script');
    script.src = 'https://control.msg91.com/app/assets/otp-provider/otp-provider.js';
    script.async = true;
    document.body.appendChild(script);

    // 2. Define the callback for MSG91 successful OTP verification 
    window.msg91Callback = async (data) => {
      // MSG91 returns a tokenAuth (request_id) upon success
      if (data && data.message && data.message.type === 'success') {
        try {
          // Send the internal requestId generated by the widget to our backend
          const response = await axios.post(
            'http://localhost:5000/api/auth/verify-phone-otp', 
            { requestId: data.message.tokenAuth },
            { headers: { Authorization: `Bearer ${token}` } } // Current logged in user token
          );
          
          if (response.data.success) {
             setIsVerified(true);
             setError('');
          }
        } catch (err) {
          setError(err.response?.data?.message || 'Verification failed on our servers');
        }
      } else {
        setError('Verification failed or cancelled by user');
      }
    };

    // 3. Initialize Settings Config
    window.initOTPWidget = () => {
      let configuration = {
        widgetId: "36636e6561473432333343233",
        tokenAuth: "CLIENT_GENERATED_SESSION_TOKEN", // An optional token from the frontend state
        success: (data) => {
           window.msg91Callback(data);
        },
        failure: (error) => {
           setError('MSG91 Widget Error: ' + error.message);
        }
      };
      
      if (window.initSendOTP) {
        window.initSendOTP(configuration);
      }
    };

    return () => {
       // Cleanup script on unmount
       document.body.removeChild(script);
       delete window.msg91Callback;
       delete window.initOTPWidget;
    };
  }, [token]);

  return (
    <div className="phone-verification-container">
      <h3>Verify your Phone Number</h3>
      
      {isVerified ? (
        <div className="alert alert-success">Phone Number Verified Successfully!</div>
      ) : (
        <>
          {error && <div className="alert alert-danger">{error}</div>}
          <button 
             onClick={() => window.initOTPWidget && window.initOTPWidget()}
             className="btn btn-primary"
          >
            Verify Phone with MSG91
          </button>
        </>
      )}
    </div>
  );
};

export default PhoneVerification;
